############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
  - path: github.comn/HugoBlox/hugo-blox-builder/main/modules/blox-tailwind/assets/css/theme/rose.css

# Install any Hugo Blox within the `hugo-blox/blox/` folder
mounts:
  - source: hugo-blox/blox/community
    target: layouts/partials/blox/community/
    includeFiles: '**.html'
  - source: hugo-blox/blox/all-access
    target: layouts/partials/blox/
    includeFiles: '**.html'
  - source: hugo-blox/blox
    target: assets/dist/community/blox/
    includeFiles: '**.css'
  - source: layouts
    target: layouts
  - source: assets
    target: assets
